theme: jekyll-theme-cayman

# Setup

title:        "Haven: Keep Watch, Stay Safe"
tagline:      "Haven is for people who need a way to protect their personal spaces and possessions without compromising their own privacy."
baseurl:      ""
paginate:     1
locale: "en"

# About/contact
author:
  name:       Guardian Project
  url: https://guardianproject.info/contact

#show_downloads: true
